trigger:
- main

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- script: conda env create --quiet --file conda.yaml
  displayName: Create Anaconda environment

- bash: |
    source activate mtg-artist-data
    python -m mtg_data_code/upload_data_to_blob
  displayName: Upload Data
  env:
    BLOB_CONNECTION_STRING: $(BLOB_CONNECTION_STRING)
