name: mtg-artist-data
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=24.0
  - python=3.10.14
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - adlfs==2024.4.1
      - aiohttp==3.9.5
      - aiohttp-retry==2.8.3
      - aiosignal==1.3.1
      - amqp==5.2.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - argcomplete==3.3.0
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - asyncssh==2.14.2
      - atpublic==4.1.0
      - attrs==23.2.0
      - azure-core==1.30.1
      - azure-datalake-store==0.0.53
      - azure-identity==1.16.0
      - azure-storage-blob==12.20.0
      - billiard==4.2.0
      - celery==5.4.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - colorama==0.4.6
      - comm==0.2.2
      - configobj==5.0.8
      - cryptography==42.0.7
      - debugpy==1.8.1
      - decorator==5.1.1
      - dictdiffer==0.9.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dpath==2.1.6
      - dulwich==0.22.1
      - dvc==3.51.0
      - dvc-azure==3.1.0
      - dvc-data==3.15.1
      - dvc-http==2.32.0
      - dvc-objects==5.1.0
      - dvc-render==1.0.2
      - dvc-studio-client==0.20.0
      - dvc-task==0.4.0
      - entrypoints==0.4
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - filelock==3.14.0
      - flatten-dict==0.4.2
      - flufl-lock==7.1.1
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - funcy==2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grandalf==0.8
      - gto==1.7.1
      - hydra-core==1.3.2
      - idna==3.7
      - ipykernel==6.29.4
      - ipython==8.24.0
      - isodate==0.6.1
      - iterative-telemetry==0.0.8
      - jedi==0.19.1
      - jmespath==1.0.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - knack==0.11.0
      - kombu==5.3.7
      - markdown-it-py==3.0.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - msal==1.28.0
      - msal-extensions==1.1.0
      - mtgsdk==1.3.1
      - multidict==6.0.5
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numpy==1.26.4
      - omegaconf==2.3.0
      - orjson==3.10.3
      - packaging==24.0
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - platformdirs==3.11.0
      - portalocker==2.8.2
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.22
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pydot==2.0.0
      - pygit2==1.15.0
      - pygments==2.18.0
      - pygtrie==2.5.0
      - pyjwt==2.8.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - requests==2.32.2
      - rich==13.7.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - scmrepo==3.3.5
      - semver==3.0.2
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.7.1
      - six==1.16.0
      - smmap==5.0.1
      - sqltrie==0.11.0
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tomlkit==0.12.5
      - tornado==6.4
      - tqdm==4.66.4
      - traitlets==5.14.3
      - typer==0.12.3
      - typing-extensions==4.12.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - vine==5.1.0
      - voluptuous==0.14.2
      - wcwidth==0.2.13
      - yarl==1.9.4
      - zc-lockfile==3.0.post1
